### ISSUE TITLE
Does expect-error flag work?

### ISSUE THREAD

**Issue by DavieReid** [aikoven/typings-tester#2]
Interested in using this tool to validate manually created definition files.

I have everything set up and I am using TypeScript 2.7.2.

Using the example from the readme:
`// typings:expect-error
function shouldFail(a: number): string {
  return a;
}`

I get the following error:

`typings-tester --config ../../typings.tsconfig.json ./typings/panel.test.tsx
Semantic: typings/panel.test.tsx (51, 3) Type 'number' is not assignable to type 'string'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Does the flag work?

**Comment by aikoven** [comment]
It should work, at least all tests pass.

Could you please share your `tsconfig.json` and typings file?

**Comment by DavieReid** [comment]
Hi, thanks for the response.

I am no longer exploring this as an option.
