### ISSUE TITLE
Support for Typescript 3

### ISSUE THREAD

**Issue by gwillz** [aikoven/typings-tester#4]
By 'support', I mean, tweak the peer dependencies.

Currently, peer dependencies requires `~2` and triggers warnings when installing, but still works fine. 

I don't believe Typescript strictly follows semantic versioning. So v3 is really a v2.10 and hasn't got any API breaking changes.

**Comment by aikoven** [comment]
Thanks for the issue, I've updated TypeScript version in `peerDependencies` to `~2 || ~3` in `typings-tester@0.3.2`.
